#pragma once
#include "ScoreSerializer.h"
#include "Application.h"

namespace MikuMikuWorld
{
	struct SUS;

	class SusSerializer : public ScoreSerializer
	{
		std::string exportComment;

	  public:
		SusSerializer()
		{
			exportComment = "This file was generated by " APP_NAME " " +
			                Application::getInstance().getAppVersion();
		}

		static SerializingScore susToScore(const SUS& sus);
		static SUS scoreToSus(const SerializingScore& data);

		void serialize(const SerializingScore& data, std::string filename) override;
		SerializingScore deserialize(std::string filename) override;

		static Result canSerialize(const SerializingScore& score);
	};
}
